// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuciaefueqwdmwvxhevw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1Y2lhZWZ1ZXF3ZG13dnhoZXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNjQ4NjksImV4cCI6MjA1Mzk0MDg2OX0.cUhowojHF2w84Sj3uC4OkC88GkjVduKFsf89V0kHhwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);